version: '2'

services:
  ca.example.com:
    image: hyperledger/fabric-ca:latest
    container_name: ca.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_LOGLEVEL=DEBUG
    ports:
      - 7054:7054
    volumes:
      - ./fabric-ca:/etc/hyperledger/fabric-ca
